# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3c353b613f55ddf577658897584b001f"
name = "test-vercel-app"
application_url = "https://ab-loose-ind-jury.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "krb-kuro.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products"

[auth]
redirect_urls = [
  "https://ab-loose-ind-jury.trycloudflare.com/auth/callback",
  "https://ab-loose-ind-jury.trycloudflare.com/auth/shopify/callback",
  "https://ab-loose-ind-jury.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
